<!DOCTYPE Guests [
        <!ELEMENT Guests (item)*>
        <!ELEMENT item (id|firstName|lastName)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT firstName (#PCDATA)>
        <!ELEMENT lastName (#PCDATA)>
        ]>
<Guests>
    <item>
        <id>0</id>
        <firstName>John</firstName>
        <lastName>Doe</lastName>
    </item>
    <item>
        <id>0</id>
        <firstName>María</firstName>
        <lastName>García</lastName>
    </item>
    <item>
        <id>0</id>
        <firstName>Nikki</firstName>
        <lastName>Wolf</lastName>
    </item>
</Guests>